//https://en.wikipedia.org/wiki/Category:Fish_common_names
var fishNames = [
"Albanian roach",
"Algae eater",
"Armoured catfish",
"Asian carp",
"Barb",
"Barbel",
"B$ass",
"Basslet",
"Billfish",
"Black bream",
"Black pacu",
"Blennioidei",
"Blenny",
"Bluefin tuna",
"Bream",
"Brown stingray",
"Bumblebee catfish",
"Carp",
"Cavalla",
"Cave catfish",
"Chub",
"Coachwhip ray",
"Crampfish",
"Darter",
"Dogfish",
"Dory",
"Dwarf cichlid",
"Dwarf snakeheads",
"False Tasmanian blenny",
"Fierasfer",
"Flagtail pipefish",
"Flathead",
"Flounder",
"Freshwater shark",
"Grayback",
"Green spotted puffer",
"Grouper",
"Gudgeon",
"Hake",
"Halibut",
"Hamour",
"Haplochromine",
"Hawaiian flagtail",
"Headstander",
"Herring",
"Highfin snapper",
"Horned blenny",
"Horse mackerel",
"Killifish",
"Lampfish",
"List of common commercial of Sri Lanka",
"List of Danionin species by common name",
"Logperch",
"Lungfish",
"Mackerel",
"Mahseer",
"Mbuna",
"Menhaden",
"Minnow",
"Oyster blenny",
"Pacu",
"Perch",
"Piper",
"Plaice",
"Platy",
"Porgi grunt",
"Raphael catfish",
"Rasbora",
"Red mullet",
"Red seabream",
"Red Snapper",
"Redfish",
"Sábalo",
"Sailfin catfish",
"Salmon",
"Sand eel",
"Sardine",
"Scissortail rasbora",
"Scrod",
"Shiner",
"Silver bream",
"Silver dollar",
"Silver",
"Snakefish",
"Sole",
"Southern hake",
"Sprat",
"Stingfish",
"Suckermouth",
"Suckermouth catfish",
"Tetra",
"Tigerfish",
"Tilapia",
"Toadfish",
"Toado",
"Trout",
"Upside-down catfish",
"Utaka",
"Whiff",
"Whitefish (fisheries term)",
"Whiting",
"Yellow catfish",
"Yellowfin bream",
"Yellowtail"
];

//http://www.gingersoftware.com/content/grammar-rules/adjectives/lists-of-adjectives/
var adjectives = [
"fast",
"quick",
"rapid",
"slow",
"swift",
"adorable",
"beautiful",
"clean",
"drab",
"elegant",
"fancy",
"glamorous",
"handsome",
"long",
"agreeable",
"brave",
"calm",
"delightful",
"eager",
"faithful",
"gentle",
"happy",
"jolly",
"kind",
"lively",
"nice",
"obedient",
"proud",
"relieved",
"silly",
"thankful",
"victorious",
"witty",
"zealous",
"big",
"colossal",
"fat",
"gigantic",
"great",
"huge",
"immense",
"large",
"little",
];

String.prototype.capitalizeFirstLetter = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
};

var randomName = function(){
   var name = randomArray(adjectives).capitalizeFirstLetter() +
    " "+
    randomArray(fishNames).toLowerCase();
    return name;
};
